### ISSUE TITLE
[BUG]<bd.bangbang93.com>当日请求数计算错误

### ISSUE THREAD

**Issue by zyxkad** [bangbang93/openbmclapi#15]
# 如题

### 列表中显示, 当日请求数为2923
![image](https://user-images.githubusercontent.com/91082411/137647955-e5d9b89d-d619-4f0c-a53a-ef8e4c3ea2a6.png)

### 而图表中却显示, 当日请求约为2.92万 = 29200
![image](https://user-images.githubusercontent.com/91082411/137647965-dfd24a18-a917-430b-89db-ef56a6acc2cb.png)

**Comment by zyxkad** [comment]
貌似解决了, 也不来关一下issue:<

**Comment by bangbang93** [comment]
已修复
