### ISSUE TITLE
[FUTURE]</openbmclapi/files>文件列表分片

### ISSUE THREAD

**Issue by zyxkad** [bangbang93/openbmclapi#16]
当我请求`/openbmclapi/files`时，至少需要等待20s  
而这20s内请求的数据99%都是不必要的  
所以我建议将`/openbmclapi/files`进行分片处理，以便于节点缓存

如:  
2021年10月更新的数据存放至`/openbmclapi/files/202110.json`  
文件格式如:
```javascript
{
  "new": [{"size":1024, "hash":"00112233445566778899", "path":"/maven/com/***"},{"size":2048, "hash":"00221133445566778899", "path":"/00/221133445566778899"}],
  "del": ["[file hash]", "00112233445566779988"]
}
```

**Comment by bangbang93** [comment]
除了全量节点，每台节点持有的文件都可能是不一样的

**Comment by bangbang93** [comment]
![image](https://user-images.githubusercontent.com/3430784/137838718-6a0da8b5-8240-448d-bf4f-d652e7ea567d.png)
你是否没启用gz或者json处理速度太慢，这个请求不应该卡20秒

**Comment by zyxkad** [comment]
> ![image](https://user-images.githubusercontent.com/3430784/137838718-6a0da8b5-8240-448d-bf4f-d652e7ea567d.png) 你是否没启用gz或者json处理速度太慢，这个请求不应该卡20秒

![image](https://user-images.githubusercontent.com/91082411/138028732-167c8866-8448-4407-b329-85bbbc024934.png)
可能是我网速较慢的原因吧

**Comment by bangbang93** [comment]
> 服务器理应保存了每个分片节点的数据，如果有新文件出现，必定会更新分片节点的文件列表。这与全量节点相同。不同之处只在于，全量节点可以共享列表，而分片节点不行

不是这样设计的，文件被划分为若干分片，节点也会随机持有若干分片，新文件会比根据平衡规则选择一个分片放入

你这样子搞还要单独给每个节点维护每次的文件差异

**Comment by bangbang93** [comment]
> > 只要用好HTTP缓存，只有第一次请求会返回完整文件列表，后续请求只要文件没有变化都是304响应
> 
> 我明白，我的问题就是，一旦有一个字符发生变化，这20秒又要重新请求一遍。虽然相比于10分钟的轮询间隔来说这20秒算不上什么，但是总让人觉得很别扭

如果文件没变化，那确实一个字符都不会变。只要有变化，那肯定是文件有变化，而且这20秒内，节点又不是不能工作

> 如果不是，那就证明主服务器还是会为每个节点维护文件列表的
不是，但是服务器也没有给每个节点维护文件列表

> 至于单独给每个节点维护差异我觉得并不是很难，每个节点的性质是相同的，只要你能给其中任意一个节点维护差异，必定也能给所有节点维护差异，并且非常简单

只有全量节点之间可以看做性质相同，而非全量节点各个之间文件分布都是不一样的
而且由于被动同步功能的存在，甚至不能保证一小时内的文件都是相同无变化的，你想如何维护这个差异表

**Comment by bangbang93** [comment]
> > > 如果不是，那就证明主服务器还是会为每个节点维护文件列表的
> > 
> > 
> > 不是，但是服务器也没有给每个节点维护文件列表
> 
> 如果没有给节点维护列表，如何保证两次请求到的文件都是相同的呢？节点并没有告诉主服务器自己都有哪些文件

你可以看做服务器上有一个负载均衡用的哈希算法，决定了每个文件该进入那个分片，分配给哪个节点，而没有一个明确的节点文件列表存储在服务器上的任何地方
