### ISSUE TITLE
代码冗余

### ISSUE THREAD

**Issue by zyxkad** [bangbang93/openbmclapi#18]
**如题**

在`src/cluster.ts`中，可以见到如下代码
```typescript
  // L90
  const path = join(this.cacheDir, file.hash.substr(0, 2), file.hash)
```
也可以见到如下代码
```typescript
  // L268
  const path = join(this.cacheDir, this.hashToFilename(hash))
  // L394
  private hashToFilename(hash: string): string {
    return join(hash.substr(0, 2), hash)
  }
```
由此可见`L90`的效用**等同于** `L268`, `L394`的`hashToFilename`是一个简单的把*hash值*转换为*相对文件路径*的封装函数

我建议讲类似于`L90`的代码转换为类似`L268`的代码, 这样便于维护. 即便不然, 我也不认为同时存在`L90`的格式与`L268`的格式是个好想法

*所以能改就改吧*

顺便提一下 #15

**Comment by zyxkad** [comment]
另外还存在类似如下的代码
```typescript
  // L210
  public async listen(): Promise<void> {
    return new Promise((resolve) => {
      this.server.listen(this._port, resolve)
    })
  }
```
***async***关键字已经声明了这个方法是一个**异步方法**, 但又直接返回了一个异步***promise对象***  
可以简化为如下
```typescript
  public async listen(): Promise<void> {
    this.server.listen(this._port, resolve)
  }
```

**Comment by bangbang93** [comment]
> 

 这个不可以，你考虑一下你的resolve从哪来

**Comment by zyxkad** [comment]
> > 
> 
> 这个不可以，你考虑一下你的resolve从哪来

aw没注意, 那就
```typescript
public listen(): Promise<void>{
  return new Promise((resolve) => {
    this.server.listen(this._port, resolve)
  })
}
```

**Comment by bangbang93** [comment]
<https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/promise-function-async.md>
