### ISSUE TITLE
奇怪的崩溃

### ISSUE THREAD

**Issue by shenjackyuanjie** [bangbang93/openbmclapi#25]
![image](https://user-images.githubusercontent.com/54507071/201501529-3c73f7e3-4006-4f11-8075-c98fbd7ded9b.png)
![image](https://user-images.githubusercontent.com/54507071/201501534-bae1a02d-0af0-4062-b88f-262308407be0.png)

**Comment by bangbang93** [comment]
已更换zstd实现，再观察一段时间看看，如果有问题就reopen
