### ISSUE TITLE
更短的崩溃重启间隔

### ISSUE THREAD

**Issue by z0z0r4** [bangbang93/openbmclapi#26]
https://github.com/bangbang93/openbmclapi/blob/f73d5e1b13952916d4819ea0b4a7c6f1dc81aadd/src/index.ts#L29
60s 也太长了...希望能够在 `.env` 自定义

**Comment by bangbang93** [comment]
重启太快对服务器压力大，没必要
如果经常重启那应该解决的是经常重启的问题
