### ISSUE TITLE
BMCLAPI?

### ISSUE THREAD

**Issue by poopingpenis** [bangbang93/openbmclapi#3]
Hey so,

I found BMCLAPI on HMCL and noticed how useful it could be for me. I'd like to host Mojang update files on my own local network as well. Is the software you're using for this open-source? I found this but it seems to be something different, but then, there's no English documentation so I don't know.

Is this what I'm looking for?

**Comment by bangbang93** [comment]
Sorry, this project(OpenBMCLAPI) is not what you want.
BMCLAPI is that you need, which mirroring the assets and library of mojang and forge. But BMCLAPI project is not open-sourced.
This project is using for sharing the server of BMCLAPI bandwidth. It cannot work without the BMCLAPI core service.

**Comment by poopingpenis** [comment]
Ah, I see, thanks for the heads up. 👍
