### ISSUE TITLE
节点启用后，获取损坏的文件时有概率重定向到自己

### ISSUE THREAD

**Issue by zyxkad** [bangbang93/openbmclapi#36]
# 描述

如题，节点启用后同步文件时有很小的概率获取到重定向到自己的链接，由于没有该资源就会重复请求，然后接着重复。。。

如果bmclapi主机没有足够的流量（或者一直选择重定向到某个节点），加入新文件时可能会导致无限循环的问题（不仅仅在一个节点内跳，可能是多个节点互相跳）。
目前该可能尚未发生

# 可能修复方法

在 [`cluster.ts#L300`](https://github.com/bangbang93/openbmclapi/blob/master/src/cluster.ts#L300) 检查该文件的下载请求是否已经发起了超过3次，如果超过则：
- 报错
- 下次请求时添加一个header/param强制从主服务器下载

**Comment by bangbang93** [comment]
[cluster.ts#L300](https://github.com/bangbang93/openbmclapi/blob/master/src/cluster.ts#L300)
这里对应的服务器上的路由，是不会被发送给其他节点的，会直接返回文件内容

**Comment by zyxkad** [comment]
啊是吗，那应该是巧合，我下载文件的时候刚巧也有人从我这里下载文件。

不过真的有人下载forge1.6.4么

**Comment by zyxkad** [comment]
不对，我刚看了下IP和UA, 就是我自己下载的我自己

**Comment by zyxkad** [comment]
额明白了，L300对应的路由应该不会重定向，但是文件同步的时候走的不是L300的路由
