### ISSUE TITLE
feat: 添加 CORS 响应头部

### ISSUE THREAD

**Issue by SerinaNya** [bangbang93/openbmclapi#41]
希望能添加以下 HTTP 头部。

 ```Access-Control-Allow-Origin: *```

我正在进行前端项目开发，用户将通过浏览器对 BMCLAPI 发起请求。  
由于 CORS 策略，浏览器禁止了跨域请求，这造成了不小的麻烦。

添加此头部并允许跨域请求几乎不会造成什么不良影响。

**Comment by bangbang93** [comment]
什么网站需要用到BMCLAPI的数据？

**Comment by SerinaNya** [comment]
> 什么网站需要用到BMCLAPI的数据？

开发文档中需要通过 BMCLAPI 更快速&稳定地获取 authlib-injector 的最新版本信息。

`https://bmclapi2.bangbang93.com/mirrors/authlib-injector/artifact/latest.json`

**Comment by bangbang93** [comment]
简单GET请求不需要设置CORS头，你是否传入了一些特殊参数？

**Comment by zyxkad** [comment]
> 简单GET请求不需要设置CORS头，你是否传入了一些特殊参数？

<img width="660" alt="Screenshot 2024-02-29 at 19 27 44" src="https://github.com/bangbang93/openbmclapi/assets/91082411/9a8c9131-a90d-4fa9-a4f2-0fc0e5958c12">

@bangbang93 是需要的

**Comment by zyxkad** [comment]
好吧，还真不需要，这是github特殊设置的问题

**Comment by bangbang93** [comment]
这个不是CORS的错误，是你的源站的内容安全策略

**Comment by SerinaNya** [comment]
```
fetch('https://bmclapi2.bangbang93.com/mirrors/authlib-injector/artifact/latest.json')
```

![image](https://github.com/bangbang93/openbmclapi/assets/34389622/3e02ca74-9c8c-44b5-9f1b-8159e1134144)

👆 并未被判定为简单请求，依旧需要 CORS 头才能完成请求。望添加 CORS 头部

**Comment by bangbang93** [comment]
不想添加*，给个域名，我做白名单

**Comment by SerinaNya** [comment]
> 不想添加*，给个域名，我做白名单

写特定域名进去不太好吧。。。

如果要白名单的话需要一些时间，届时确定了域名才能给出，到时再 comment

**Comment by bangbang93** [comment]
更好的方式是自行处理代理并且缓存

**Comment by SerinaNya** [comment]
> 更好的方式是自行处理代理并且缓存

确实是
