### ISSUE TITLE
非常抱歉在这里反馈问题，因为我没能成功注册您的论坛账户

### ISSUE THREAD

**Issue by Roberta001** [bangbang93/openbmclapi#53]
在我尝试注册您的论坛时，即使密码是重复的，他依然提示“两次输入密码不一致”

**Comment by Roberta001** [comment]
这是我第一次使用github的issues，可能没能很好的利用它，非常抱歉

**Comment by Roberta001** [comment]
同时我还有一些问题想要询问，我的服务器位于海口，有域名，免备案，我可以为bmclapi腾出大概30GB左右的空间，上传速度最高11mbps（测速网测速结果），8h16GB（但是同时还在运行一个Minecraft服务器，人数不会超过6），系统是windows server 2012，每天大约有15分钟左右的时间会离线，请问这符合要求吗？

**Comment by zyxkad** [comment]
30GB可以做分片，全量需要130GB左右

**Comment by zyxkad** [comment]
上行最低速度要求10MB/s, 11mbps够了，但是测速的时候会有点悬

**Comment by Roberta001** [comment]
> 30GB可以做分片，全量需要130GB左右

我可以尝试为服务器添加100GB空间
另：请问你们有其他的联系方式吗？

**Comment by zyxkad** [comment]
有的，QQ群: 689855839

**Comment by Roberta001** [comment]
> 有的，QQ群：689855839

我已经发出申请了，麻烦通过一下，谢谢
