### ISSUE TITLE
我希望OpenBMCLAPI支持使用S3和openstack对象存储来改进镜像服务器下发文件。

### ISSUE THREAD

**Issue by linecorporation** [bangbang93/openbmclapi#55]
我希望OpenBMCLAPI支持使用S3和openstack对象存储来改进镜像服务器下发文件。

原因：
使用对象存储分发文件会有诸多好处，比如更大的带宽以及更好的IOPS性能。通过支持S3和openstack对象存储，服主可以更直观的从云服务商提供的额外功能更好的统计和分析日志信息。

需要注意的其他事项：
在Local Area Network环境下的S3和openstack服务器，会因为NAT回流导致一些问题。

I would like OpenBMCLAPI to support the use of S3 and openstack object storage to improve the mirroring server for downloading files.

Reason:
There are numerous benefits to using object storage to distribute files, such as greater bandwidth and better IOPS performance. By supporting S3 and openstack object storage, service owners can more intuitively get better statistics and analyze log information from additional features provided by the cloud provider.

Other things to keep in mind:
S3 and openstack servers in Local Area Network environments can cause some issues due to NAT backflow.

**Comment by bangbang93** [comment]
云厂商的对象存储一般不算便宜，待有其他实际途径的时候再做实现

**Comment by linecorporation** [comment]
> 云厂商的对象存储一般不算便宜，待有其他实际途径的时候再做实现

自建对象存储，不包含CDN，有Docker容器可以实现自建S3 compatible对象存储
