### ISSUE TITLE
增加日志输出功能

### ISSUE THREAD

**Issue by Anythingteam** [bangbang93/openbmclapi#59]
可选择是否输出日志

**Comment by HappyMC-Dev** [comment]
该项目README有写：
### Docker Compose
请先根据 [设置参数](#设置参数) 中说明的内容创建 `.env` 文件或直接更改 `docker-compose.yml` 文件, 然后运行以下命令:

```bash
docker compose up -d
```

## 配置

| 环境变量                | 必填 | 默认值          | 说明                                                                                                     |
|---------------------|----|--------------|--------------------------------------------------------------------------------------------------------|
| CLUSTER_ID          | 是  | -            | 集群 ID                                                                                                  |
| CLUSTER_SECRET      | 是  | -            | 集群密钥                                                                                                   |
| CLUSTER_IP          | 否  | 出口IP         | 集群 IP                                                                                                  |
| CLUSTER_PORT        | 否  | 4000         | 监听端口                                                                                                   |
| CLUSTER_PUBLIC_PORT | 否  | CLUSTER_PORT | 对外端口                                                                                                   |
| CLUSTER_BYOC        | 否  | false        | 是否使用自定义域名, (BYOC=Bring you own certificate),当使用国内服务器需要备案时, 需要启用这个参数来使用你自己的域名, 并且你需要自己提供ssl termination |
| ENABLE_NGINX        | 否  | false        | 使用 nginx 提供文件服务                                                                                        |
| DISABLE_ACCESS_LOG  | 否  | false        | 禁用访问日志输出                                                                                               |

如果你在源码中发现了其他环境变量, 那么它们是为了方便开发而存在的, 可能会随时修改, 不要在生产环境中使用

**Comment by bangbang93** [comment]
你要输出什么日志？

**Comment by Anythingteam** [comment]
::ffff:220.195.74.11 - - [27/Feb/2024:11:28:36 +0000] "GET /download/f85e4f86826405a97d929e16f60a8a2fddc7abc0?name=f85e4f86826405a97d929e16f60a8a2fddc7abc0&s=zEh_yMwQXZLZgxcW6j9Mt29klLI&e=lt4ahma1 HTTP/1.1" 206 32474 "-" "PCL2/2.6.14.50 Mozilla/5.0 AppleWebKit/537.36 Chrome/63.0.3239.132 Safari/537.36"这样的，想做个统计

**Comment by bangbang93** [comment]
你这不是已经拿到日志了

**Comment by linecorporation** [comment]
你可以使用第三方可信的Docker管理面板来取得日志。
我给你做一些推荐：Portainer和1Panel
请注意：这两个面板获取日志需要等待，因为日志不是现成的，需要等待换成完毕才能导出日志。
