### ISSUE TITLE
是否为openbmclapi添加一个分布试的玩法

### ISSUE THREAD

**Issue by qiaoliangXgamemode** [bangbang93/openbmclapi#6]
为openbmclapi添加一个Json让他自动统计全球部署的附近下载站点通过这个获取到相近的服务器从而达到缓解请求服务器的延迟和下载速度，毕竟一直请求一推官方服务器不是办法这样容易导致需要更多服务器，希望能把这个弄成分布式在一个服务器内存储大量分布的IP并且加密防止更多人取攻击或者解析出来分享

**Comment by bangbang93** [comment]
openbmclapi本来就是分布式下载的计划

 > 为openbmclapi添加一个Json让他自动统计全球部署的附近下载站点通过这个获取到相近的服务器从而达到缓解请求服务器的延迟和下载速度

GeoIP是有计划的

> 毕竟一直请求一推官方服务器不是办法这样容易导致需要更多服务器

核心服务器目前高峰期大约400QPS，负载大约六分之一，在很长一段时间内应该都是够用的

> 希望能把这个弄成分布式在一个服务器内存储大量分布的IP并且加密防止更多人取攻击或者解析出来分享

启动器想要请求这个ip，就一定得能解密，这里加密没有什么意义啊

我觉得你想表达的是不是让启动器获取到所有的节点，然后自主选择源？但是目前openbmclapi有很多节点其实并没有存储所有文件（所有文件大约有70GB），所以没法让只有服务器知道哪些文件在哪些节点上，没法让启动器自行选择。

**Comment by qiaoliangXgamemode** [comment]
草,是我错了
