### ISSUE TITLE
删除cache文件夹里expire的文件时，需要用户授权

### ISSUE THREAD

**Issue by linecorporation** [bangbang93/openbmclapi#64]
我注意到1.9.7运行时，会删除过期的文件
我希望增加用户授权
也就是先标记出expire的文件
让用户输入y（删除）/n（略过）决定操作（方便用户移动文件到别的地方）

只要分发的文件没有问题，就不管

但是目前来看这个重新会删除认为是expire的文件

**Comment by zyxkad** [comment]
openbmclapi是一个自动的服务端程序，不是个交互程序。。。 😅

**Comment by linecorporation** [comment]
这个功能有助于让用户发现异常文件，并可以让用户将文件移出

**Comment by linecorporation** [comment]
> 我注意到1.9.7运行时，会删除过期的文件 我希望增加用户授权 也就是先标记出expire的文件 让用户输入y（删除）/n（略过）决定操作（方便用户移动文件到别的地方）
> 
> 只要分发的文件没有问题，就不管
> 
> 但是目前来看这个重新会删除认为是expire的文件

如果没有选择，就自动选择n

**Comment by bangbang93** [comment]
cache目录本来就不应当由用户自行处理任何操作，整个程序设计上就是无人值守的。
默认不删除会造成磁盘空间越用越大

**Comment by linecorporation** [comment]
这个issue的目的是防止用户不小心把重要数据移动到cache文件夹导致文件被删。给一定的反悔功能

**Comment by zyxkad** [comment]
> 这个issue的目的是防止用户不小心把重要数据移动到cache文件夹导致文件被删。给一定的反悔功能

建议做全盘备份，而不是依赖特定程序不工作

**Comment by linecorporation** [comment]
事实上在Linux服务器上使用Btrfs有一定麻烦

**Comment by linecorporation** [comment]
就算不做yn决策的话，我也希望他sleep一段时间让用户自己移动文件，然后它再自动删除

这个issue的主要目的是，在删除之前给一个足够的时间

**Comment by zyxkad** [comment]
为啥你的操作会那么巧，刚好在gc的时候把文件mv过去
