### ISSUE TITLE
如何与您取得联系

### ISSUE THREAD

**Issue by database-mysql** [bangbang93/openbmclapi#67]
您好，我部署了openbmclapi，其中的CLUSTER_ID和CLUSTER_SECRET我没有，我该如和跟您联系？我的QQ号：2103932993；微信ID：gtb520_gtb520；邮箱：root@gtb520.top；

**Comment by Dongyanmio** [comment]
> 您好，我部署了openbmclapi，其中的CLUSTER_ID和CLUSTER_SECRET我没有，我该如和跟您联系？我的QQ号：2103932993；微信ID：gtb520_gtb520；邮箱：[root@gtb520.top](mailto:root@gtb520.top)；

去 689855839 这个QQ群找群主要
