### ISSUE TITLE
keep alive 时有几率报错

### ISSUE THREAD

**Issue by MicIsHere** [bangbang93/openbmclapi#71]
使用v1.10.5版本
[2Kopenbmclapi  | [2024-05-12 03:50:54.086 +0000] INFO (103): keep alive success, serve 2890 files, 2.83 GiB
[2Kopenbmclapi  | [2024-05-12 03:51:54.156 +0000] INFO (103): keep alive success, serve 3158 files, 2.53 GiB
[2Kopenbmclapi  | [2024-05-12 03:52:54.235 +0000] INFO (103): keep alive success, serve 3137 files, 2.43 GiB
[2Kopenbmclapi  | [2024-05-12 03:53:54.303 +0000] INFO (103): keep alive success, serve 3140 files, 2.56 GiB
[2Kopenbmclapi  | [2024-05-12 03:54:54.374 +0000] INFO (103): keep alive success, serve 3164 files, 3.54 GiB
[2Kopenbmclapi  | [2024-05-12 03:55:54.444 +0000] INFO (103): keep alive success, serve 2901 files, 3.3 GiB
[2Kopenbmclapi  | [2024-05-12 03:56:54.511 +0000] INFO (103): keep alive success, serve 2681 files, 2.57 GiB
[2Kopenbmclapi  | [2024-05-12 03:57:54.579 +0000] INFO (103): keep alive success, serve 3051 files, 3.08 GiB
[2Kopenbmclapi  | RangeNotSatisfiableError: Range Not Satisfiable
[2Kopenbmclapi  |     at createHttpError (/app/node_modules/express/node_modules/send/index.js:984:7)
[2Kopenbmclapi  |     at SendStream.error (/app/node_modules/express/node_modules/send/index.js:270:31)
[2Kopenbmclapi  |     at SendStream.send (/app/node_modules/express/node_modules/send/index.js:666:19)
[2Kopenbmclapi  |     at onstat (/app/node_modules/express/node_modules/send/index.js:725:10)
[2Kopenbmclapi  |     at FSReqCallback.oncomplete (node:fs:205:5)
[2Kopenbmclapi  | [2024-05-12 03:58:54.647 +0000] INFO (103): keep alive success, serve 3009 files, 2.46 GiB
[2Kopenbmclapi  | [2024-05-12 03:59:54.715 +0000] INFO (103): keep alive success, serve 3436 files, 3.05 GiB
[2Kopenbmclapi  | [2024-05-12 04:00:54.785 +0000] INFO (103): keep alive success, serve 3360 files, 3.08 GiB
[2Kopenbmclapi  | RangeNotSatisfiableError: Range Not Satisfiable
[2Kopenbmclapi  |     at createHttpError (/app/node_modules/express/node_modules/send/index.js:984:7)
[2Kopenbmclapi  |     at SendStream.error (/app/node_modules/express/node_modules/send/index.js:270:31)
[2Kopenbmclapi  |     at SendStream.send (/app/node_modules/express/node_modules/send/index.js:666:19)
[2Kopenbmclapi  |     at onstat (/app/node_modules/express/node_modules/send/index.js:725:10)
[2Kopenbmclapi  |     at FSReqCallback.oncomplete (node:fs:205:5)
[2Kopenbmclapi  | RangeNotSatisfiableError: Range Not Satisfiable
[2Kopenbmclapi  |     at createHttpError (/app/node_modules/express/node_modules/send/index.js:984:7)
[2Kopenbmclapi  |     at SendStream.error (/app/node_modules/express/node_modules/send/index.js:270:31)
[2Kopenbmclapi  |     at SendStream.send (/app/node_modules/express/node_modules/send/index.js:666:19)
[2Kopenbmclapi  |     at onstat (/app/node_modules/express/node_modules/send/index.js:725:10)
[2Kopenbmclapi  |     at FSReqCallback.oncomplete (node:fs:205:5)
[2Kopenbmclapi  | [2024-05-12 04:01:54.856 +0000] INFO (103): keep alive success, serve 3803 files, 3.43 GiB
[2Kopenbmclapi  | RangeNotSatisfiableError: Range Not Satisfiable
[2Kopenbmclapi  |     at createHttpError (/app/node_modules/express/node_modules/send/index.js:984:7)
[2Kopenbmclapi  |     at SendStream.error (/app/node_modules/express/node_modules/send/index.js:270:31)
[2Kopenbmclapi  |     at SendStream.send (/app/node_modules/express/node_modules/send/index.js:666:19)
[2Kopenbmclapi  |     at onstat (/app/node_modules/express/node_modules/send/index.js:725:10)
[2Kopenbmclapi  |     at FSReqCallback.oncomplete (node:fs:205:5)
[2Kopenbmclapi  | [2024-05-12 04:02:54.932 +0000] INFO (103): keep alive success, serve 3651 files, 3.2 GiB
[2Kopenbmclapi  | RangeNotSatisfiableError: Range Not Satisfiable
[2Kopenbmclapi  |     at createHttpError (/app/node_modules/express/node_modules/send/index.js:984:7)
[2Kopenbmclapi  |     at SendStream.error (/app/node_modules/express/node_modules/send/index.js:270:31)
[2Kopenbmclapi  |     at SendStream.send (/app/node_modules/express/node_modules/send/index.js:666:19)
[2Kopenbmclapi  |     at onstat (/app/node_modules/express/node_modules/send/index.js:725:10)
[2Kopenbmclapi  |     at FSReqCallback.oncomplete (node:fs:205:5)
[2Kopenbmclapi  | [2024-05-12 04:03:55.016 +0000] INFO (103): keep alive success, serve 3746 files, 3.2 GiB
[2Kopenbmclapi  | [2024-05-12 04:04:55.086 +0000] INFO (103): keep alive success, serve 3542 files, 3.71 GiB
[2Kopenbmclapi  | RangeNotSatisfiableError: Range Not Satisfiable
[2Kopenbmclapi  |     at createHttpError (/app/node_modules/express/node_modules/send/index.js:984:7)
[2Kopenbmclapi  |     at SendStream.error (/app/node_modules/express/node_modules/send/index.js:270:31)
[2Kopenbmclapi  |     at SendStream.send (/app/node_modules/express/node_modules/send/index.js:666:19)
[2Kopenbmclapi  |     at onstat (/app/node_modules/express/node_modules/send/index.js:725:10)
[2Kopenbmclapi  |     at FSReqCallback.oncomplete (node:fs:205:5)
[2Kopenbmclapi  | [2024-05-12 04:05:55.157 +0000] INFO (103): keep alive success, serve 3652 files, 3.34 GiB
[2Kopenbmclapi  | [2024-05-12 04:06:55.238 +0000] INFO (103): keep alive success, serve 3500 files, 3.31 GiB
[2Kopenbmclapi  | [2024-05-12 04:07:55.308 +0000] INFO (103): keep alive success, serve 3685 files, 3.19 GiB
[2Kopenbmclapi  | [2024-05-12 04:08:55.376 +0000] INFO (103): keep alive success, serve 3705 files, 2.86 GiB
[2Kopenbmclapi  | [2024-05-12 04:09:55.446 +0000] INFO (103): keep alive success, serve 3946 files, 3.12 GiB

**Comment by bangbang93** [comment]
不用管
