### ISSUE TITLE
Problem with BMCL API !

### ISSUE THREAD

**Issue by BANSAFAn** [bangbang93/openbmclapi#84]
Let me get this straight! There is one launcher that uses BMCL API, but that's not the point, but what is just interesting is whether BMCL API can block some regions ? 

We encountered this problem recently and just got curious, just when trying to select Optifine, we were given this:
![изображение](https://github.com/user-attachments/assets/06be668a-3e95-47a4-99e4-a63c2d57b918)

The mistake itself: Error: Failed to load https://bmclapi2.bangbang93.com/optifine/versionList
    at Jr (http://xmcl.runtime/assets/index.3449731a.js:1:36062)
    at async fetcher (http://xmcl.runtime/assets/index.3449731a.js:1:41147)
    
    
 Is this a bug on your part or the launcher ?

**Comment by bangbang93** [comment]
BMCLAPI surfaced in some network attacks last week. So now block some IP ranges that are not in China mainland.
This restriction will be removed in some weeks.
