### ISSUE TITLE
全量同步文件报错

### ISSUE THREAD

**Issue by stydxm** [bangbang93/openbmclapi#9]
文档结尾写道：
> openbmclapi会自行同步需要的文件，但是初次同步可能会速度过慢，如果您的节点是个全量节点，可以通过以下命令使用rsync快速同步 `rsync -azvP openbmclapi@jp.bmclapi.933.moe::openbmclapi cache`

执行命令时提示无法解析域名
![OPNRTGF%Q@~`Y I1GO2PB4E](https://user-images.githubusercontent.com/62790279/114273497-d3690800-9a4c-11eb-89bd-3659dedd399c.png)

**Comment by bangbang93** [comment]
这服务器没了……暂时还没空闲服务器支持全量快速初始化，只能慢慢同步了

**Comment by stydxm** [comment]
这样啊……那能不能打包一下传个网盘或者直接扔github page

**Comment by bangbang93** [comment]
80多个G，而且天天在更新，也不能网盘和github page都不现实

**Comment by stydxm** [comment]
好吧，谢谢了
