### ISSUE TITLE
当启用NGINX作为文件服务的时候，且使用alist存储时，稳定性严重下降

### ISSUE THREAD

**Issue by Uright-Xuqing233** [bangbang93/openbmclapi#91]
作为对比，我截取了两段log：
[disable-nginx.log](https://github.com/user-attachments/files/17009713/disable-nginx.log)
[enable-nginx.log](https://github.com/user-attachments/files/17009714/enable-nginx.log)
在不启用nginx时，服务能够长时间在线且没有http错误码地提供服务。
在启用nginx时，服务在大约半个小时内就会被强制下线一次且有大量http错误码返回。

**Comment by bangbang93** [comment]
我看你的路径并不是docker，建议提供一下nginx版本

**Comment by Uright-Xuqing233** [comment]
nginx version: nginx/1.26.2

**Comment by bangbang93** [comment]
这些个错误都是nginx返回的，你可能需要排查一下你的nginx环境问题

**Comment by Uright-Xuqing233** [comment]
emmm，好吧
