### ISSUE TITLE
How long BMCL API will not work in other countries ?

### ISSUE THREAD

**Issue by BANSAFAn** [bangbang93/openbmclapi#92]
It's been 2 weeks but people can't download optifine via BMCL, just wondering how long you have to wait.

Here's the error that pops up:

```
Error: Failed to load https://bmclapi2.bangbang93.com/optifine/versionList
    at Er (http://xmcl.runtime/assets/index.918581a4.js:1:19479)
    at async fetcher (http://xmcl.runtime/assets/index.918581a4.js:1:24564)
```

**Comment by bangbang93** [comment]
All restrictions have been removed before Oct 1st.
Please provide a log with more details or contact the xmcl team.

**Comment by BANSAFAn** [comment]
> All restrictions have been removed before Oct 1st. Please provide a log with more details or contact the xmcl team.

okey
